# Exploración del Dataset

In [1]:
import numpy as np
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import pyarrow

In [2]:
# Cargamos los datos de la tabla de galaxias centrales
data_centrales = pl.read_csv('data/tracks_centrales_snap28.csv')

# Cargamos los datos de las fusines
data_fusiones = pl.read_csv('data/historial_merger_centrales_snap28.csv')

In [3]:
# Información hisórica del desarrollo de las galaxias centrales
data_centrales

shape: (36_854, 22)
┌──────────┬─────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ GalaxyID ┆ SnapNum ┆ Redshift   ┆ Stars_Mass ┆ … ┆ BlackHole ┆ BlackHole ┆ SubHaloGa ┆ RootGalax │
│ ---      ┆ ---     ┆ ---        ┆ ---        ┆   ┆ Mass      ┆ MassAccre ┆ laxyID    ┆ yID       │
│ i64      ┆ i64     ┆ f64        ┆ f64        ┆   ┆ ---       ┆ tionRate  ┆ ---       ┆ ---       │
│          ┆         ┆            ┆            ┆   ┆ f64       ┆ ---       ┆ i64       ┆ i64       │
│          ┆         ┆            ┆            ┆   ┆           ┆ f64       ┆           ┆           │
╞══════════╪═════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 8646393  ┆ 12      ┆ 3.0165045  ┆ 1.8160373e ┆ … ┆ 149624.95 ┆ 1.0145e-1 ┆ 8646393   ┆ 8646377   │
│          ┆         ┆            ┆ 8          ┆   ┆           ┆ 0         ┆           ┆           │
│ 8646392  ┆ 13      ┆ 2.4784133  ┆ 4.0484758e ┆ … ┆ 149628.08 ┆ 2.2226e-9 ┆ 8646392   ┆ 8646377   │
│          ┆         ┆            ┆ 8          ┆   ┆           ┆           ┆           ┆           │
│ 8646391  ┆ 14      ┆ 2.237037   ┆ 6.7043725e ┆ … ┆ 149650.48 ┆ 7.4560e-9 ┆ 8646391   ┆ 8646377   │
│          ┆         ┆            ┆ 8          ┆   ┆           ┆           ┆           ┆           │
│ 8646390  ┆ 15      ┆ 2.0124102  ┆ 1.0876e9   ┆ … ┆ 149653.77 ┆ 7.1106e-9 ┆ 8646390   ┆ 8646377   │
│ 8646389  ┆ 16      ┆ 1.7369658  ┆ 1.7818e9   ┆ … ┆ 298193.6  ┆ 2.2962e-8 ┆ 8646389   ┆ 8646377   │
│ …        ┆ …       ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 21986365 ┆ 24      ┆ 0.365669   ┆ 8.0355e11  ┆ … ┆ 1.0961e9  ┆ 0.00445   ┆ 21986365  ┆ 21986361  │
│ 21986364 ┆ 25      ┆ 0.270901   ┆ 9.1478e11  ┆ … ┆ 1.1888e9  ┆ 0.012013  ┆ 21986364  ┆ 21986361  │
│ 21986363 ┆ 26      ┆ 0.18271    ┆ 1.0332e12  ┆ … ┆ 8.605493e ┆ 0.000002  ┆ 21986363  ┆ 21986361  │
│          ┆         ┆            ┆            ┆   ┆ 8         ┆           ┆           ┆           │
│ 21986362 ┆ 27      ┆ 0.100639   ┆ 1.1160e12  ┆ … ┆ 2.7360e9  ┆ 0.01378   ┆ 21986362  ┆ 21986361  │
│ 21986361 ┆ 28      ┆ 2.2204e-16 ┆ 1.2919e12  ┆ … ┆ 2.9014e9  ┆ 0.010209  ┆ 21986361  ┆ 21986361  │
└──────────┴─────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
# Historial de fusiones de las galaxias centrales
data_fusiones

shape: (55_675, 3)
┌──────────┬──────────┬──────────┐
│ GalaxyID ┆ Snapshot ┆ Lm       │
│ ---      ┆ ---      ┆ ---      │
│ i64      ┆ i64      ┆ f64      │
╞══════════╪══════════╪══════════╡
│ 8646377  ┆ 3        ┆ 1.0      │
│ 8646377  ┆ 4        ┆ 1.0      │
│ 8646377  ┆ 5        ┆ 1.0      │
│ 8646377  ┆ 6        ┆ 1.0      │
│ 8646377  ┆ 7        ┆ 1.0      │
│ …        ┆ …        ┆ …        │
│ 21986361 ┆ 24       ┆ 1.001543 │
│ 21986361 ┆ 25       ┆ 1.000458 │
│ 21986361 ┆ 26       ┆ 1.041736 │
│ 21986361 ┆ 27       ┆ 1.044029 │
│ 21986361 ┆ 28       ┆ 1.00087  │
└──────────┴──────────┴──────────┘

In [5]:
# Unimos las tablas para obtener una visión completa de la evolución de las galaxias centrales
new_data = data_centrales.join(data_fusiones, left_on=['RootGalaxyID','SnapNum'], right_on=['GalaxyID','Snapshot'], how='left')

new_data

shape: (36_854, 23)
┌──────────┬─────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬──────────┐
│ GalaxyID ┆ SnapNum ┆ Redshift   ┆ Stars_Mass ┆ … ┆ BlackHoleM ┆ SubHaloGa ┆ RootGalax ┆ Lm       │
│ ---      ┆ ---     ┆ ---        ┆ ---        ┆   ┆ assAccreti ┆ laxyID    ┆ yID       ┆ ---      │
│ i64      ┆ i64     ┆ f64        ┆ f64        ┆   ┆ onRate     ┆ ---       ┆ ---       ┆ f64      │
│          ┆         ┆            ┆            ┆   ┆ ---        ┆ i64       ┆ i64       ┆          │
│          ┆         ┆            ┆            ┆   ┆ f64        ┆           ┆           ┆          │
╞══════════╪═════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪══════════╡
│ 8646393  ┆ 12      ┆ 3.0165045  ┆ 1.8160373e ┆ … ┆ 1.0145e-10 ┆ 8646393   ┆ 8646377   ┆ 1.020797 │
│          ┆         ┆            ┆ 8          ┆   ┆            ┆           ┆           ┆          │
│ 8646392  ┆ 13      ┆ 2.4784133  ┆ 4.0484758e ┆ … ┆ 2.2226e-9  ┆ 8646392   ┆ 8646377   ┆ 1.208551 │
│          ┆         ┆            ┆ 8          ┆   ┆            ┆           ┆           ┆          │
│ 8646391  ┆ 14      ┆ 2.237037   ┆ 6.7043725e ┆ … ┆ 7.4560e-9  ┆ 8646391   ┆ 8646377   ┆ 1.002513 │
│          ┆         ┆            ┆ 8          ┆   ┆            ┆           ┆           ┆          │
│ 8646390  ┆ 15      ┆ 2.0124102  ┆ 1.0876e9   ┆ … ┆ 7.1106e-9  ┆ 8646390   ┆ 8646377   ┆ 1.0      │
│ 8646389  ┆ 16      ┆ 1.7369658  ┆ 1.7818e9   ┆ … ┆ 2.2962e-8  ┆ 8646389   ┆ 8646377   ┆ 1.004163 │
│ …        ┆ …       ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …        │
│ 21986365 ┆ 24      ┆ 0.365669   ┆ 8.0355e11  ┆ … ┆ 0.00445    ┆ 21986365  ┆ 21986361  ┆ 1.001543 │
│ 21986364 ┆ 25      ┆ 0.270901   ┆ 9.1478e11  ┆ … ┆ 0.012013   ┆ 21986364  ┆ 21986361  ┆ 1.000458 │
│ 21986363 ┆ 26      ┆ 0.18271    ┆ 1.0332e12  ┆ … ┆ 0.000002   ┆ 21986363  ┆ 21986361  ┆ 1.041736 │
│ 21986362 ┆ 27      ┆ 0.100639   ┆ 1.1160e12  ┆ … ┆ 0.01378    ┆ 21986362  ┆ 21986361  ┆ 1.044029 │
│ 21986361 ┆ 28      ┆ 2.2204e-16 ┆ 1.2919e12  ┆ … ┆ 0.010209   ┆ 21986361  ┆ 21986361  ┆ 1.00087  │
└──────────┴─────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴──────────┘

In [6]:
# Calculamos variables adicionales para el análisis


new_data = new_data.with_columns(
    # Logaritmos
    pl.col('Stars_Mass').log10().alias('Log(Stars_Mass)'),
    pl.col('BlackHoleMass').log10().alias('Log(BlackHoleMass)'),
    
    # Norma de Stars_Spin (usando una expresión más limpia)
    (pl.col('Stars_Spin_x')**2 + pl.col('Stars_Spin_y')**2 + pl.col('Stars_Spin_z')**2)
    .sqrt().alias('Stars_Spin_Total'),
    
    # Norma de SF_Spin
    (pl.col('SF_Spin_x')**2 + pl.col('SF_Spin_y')**2 + pl.col('SF_Spin_z')**2)
    .sqrt().alias('SF_Spin_Total'),
    
    # Norma del Spin de gas SF y Stars
    ((pl.col('SF_Spin_x')+pl.col('Stars_Spin_x'))**2 + (pl.col('SF_Spin_y')+pl.col('Stars_Spin_y'))**2 + (pl.col('SF_Spin_z')+pl.col('Stars_Spin_z'))**2)
    .sqrt().alias('Total_Spin'),
    
    # Calculo de metalicidad.
    (12 + pl.col('SF_Oxygen').log10() - pl.col('SF_Hydrogen').log10()-np.log10(16)).alias('12+log(O/H)')
)

In [ ]:
# Ploteo de algunas magnitudes

df_final = (
    new_data
    .select([
        pl.col("SnapNum"),
        pl.col("Stars_Mass").log10().alias("log_Mstar"),
        pl.col("BlackHoleMass").log10().alias("log_MBH"),
        pl.col('12+log(O/H)')
    ])
    .to_pandas() # Aquí debería funcionar si tienes pyarrow
)



fig = px.scatter(
    df_final, 
    x="log_Mstar", 
    y="12+log(O/H)", 
    animation_frame="SnapNum",  # Crea el slider temporal
    #color="SnapNum",            # Opcional: para ver el gradiente
    marginal_x="histogram",     # Distribución de X arriba
    marginal_y="violin",        # Distribución de Y a la derecha
    hover_name="SnapNum",
    range_x=[df_final["log_Mstar"].min(), df_final["log_Mstar"].max()],
    range_y=[df_final["12+log(O/H)"].min(), df_final["12+log(O/H)"].max()]
)

fig.show()