# Script para historias de merger para galaxias mayores a 10^10 en el snap 28

In [ ]:
import src.merger_tree_tools as mtt
import numpy as np
from astropy.table import Table
from astropy.cosmology import Planck15 as cosmo
import h5py
import pandas as pd

/home/ramiro/Documentos/Facultad/Datos guardados/Maestría/Taller de Tesis 1/Python Taller 1/merger_tree_tools.py:196: SyntaxWarning: invalid escape sequence '\l'
  """

In [15]:
path_lin ='data/'

In [16]:
# Tamaño de visualización de los DataFrame

pd.options.display.max_rows = 28
pd.options.display.max_columns = 50

In [34]:
table  = pd.read_csv(path_lin+'data_centrales_snap28.csv')

In [36]:
table.head(10)

,GalaxyID,GroupID,SnapNum,SubGroupNumber,Stars_Mass,BlackHoleMass,SF_Mass,SF_Oxygen,SF_Hydrogen,metalicidad
0,8646377,28000000000765,28,0,2.395396e+10,2.332017e+06,6.336636e+09,0.013817,0.680822,9.103268
1,8650718,28000000000776,28,0,2.697615e+10,1.614533e+07,3.620117e+09,0.013211,0.682108,9.082946
2,8653534,28000000000784,28,0,4.042998e+10,4.039454e+06,7.669633e+09,0.016388,0.665448,9.187281
3,8657694,28000000000789,28,0,3.519254e+10,1.686083e+07,1.586325e+09,0.022328,0.621889,9.351020
4,8664336,28000000000811,28,0,3.623367e+10,4.919216e+06,3.850225e+09,0.018820,0.649435,9.257953
5,8669006,28000000000822,28,0,2.012936e+10,2.918308e+06,4.023544e+09,0.013354,0.680497,9.088652
6,8672479,28000000000825,28,0,1.013062e+10,1.715129e+06,2.363722e+09,0.013280,0.681660,9.085519
7,8675491,28000000000835,28,0,3.593156e+10,1.468233e+07,4.860410e+09,0.016661,0.660269,9.197848
8,8681166,28000000000856,28,0,3.110775e+10,2.866600e+06,4.914577e+09,0.015695,0.667333,9.167300
9,8684780,28000000000862,28,0,2.352915e+10,5.466232e+06,5.550211e+09,0.013580,0.681025,9.095619

In [10]:
table['log(SF_Mass)']   = np.log10(table['SF_Mass'])
table['log(Stars_Mass)']= np.log10(table['Stars_Mass'])
table

,GalaxyID,GroupID,SnapNum,SubGroupNumber,Stars_Mass,BlackHoleMass,SF_Mass,SF_Oxygen,SF_Hydrogen,metalicidad,log(SF_Mass),log(Stars_Mass)
0,8646377,28000000000765,28,0,2.395396e+10,2.332017e+06,6.336636e+09,0.013817,0.680822,9.103268,9.801859,10.379377
1,8650718,28000000000776,28,0,2.697615e+10,1.614533e+07,3.620117e+09,0.013211,0.682108,9.082946,9.558723,10.430980
2,8653534,28000000000784,28,0,4.042998e+10,4.039454e+06,7.669633e+09,0.016388,0.665448,9.187281,9.884775,10.606704
3,8657694,28000000000789,28,0,3.519254e+10,1.686083e+07,1.586325e+09,0.022328,0.621889,9.351020,9.200392,10.546451
4,8664336,28000000000811,28,0,3.623367e+10,4.919216e+06,3.850225e+09,0.018820,0.649435,9.257953,9.585486,10.559112
...,...,...,...,...,...,...,...,...,...,...,...,...
2167,21379521,28000000000001,28,0,1.905425e+12,1.670998e+09,5.368436e+10,0.012449,0.695985,9.048399,10.729848,12.279992
2168,21573586,28000000000002,28,0,1.665042e+12,2.733858e+09,3.504242e+10,0.011764,0.701442,9.020433,10.544594,12.221425
2169,21730535,28000000000003,28,0,1.865954e+12,1.010321e+09,5.163819e+10,0.011853,0.704253,9.021970,10.712971,12.270901
2170,21924775,28000000000004,28,0,8.026573e+11,1.392766e+09,1.918478e+10,0.013734,0.687691,9.096283,10.282957,11.904530
2171,21986361,28000000000005,28,0,1.291893e+12,2.901400e+09,1.332103e+10,0.011223,0.700813,9.000403,10.124538,12.111226

In [11]:
table_a = table[
                (table['log(Stars_Mass)']>=10)
               ].copy()
table_a

,GalaxyID,GroupID,SnapNum,SubGroupNumber,Stars_Mass,BlackHoleMass,SF_Mass,SF_Oxygen,SF_Hydrogen,metalicidad,log(SF_Mass),log(Stars_Mass)
0,8646377,28000000000765,28,0,2.395396e+10,2.332017e+06,6.336636e+09,0.013817,0.680822,9.103268,9.801859,10.379377
1,8650718,28000000000776,28,0,2.697615e+10,1.614533e+07,3.620117e+09,0.013211,0.682108,9.082946,9.558723,10.430980
2,8653534,28000000000784,28,0,4.042998e+10,4.039454e+06,7.669633e+09,0.016388,0.665448,9.187281,9.884775,10.606704
3,8657694,28000000000789,28,0,3.519254e+10,1.686083e+07,1.586325e+09,0.022328,0.621889,9.351020,9.200392,10.546451
4,8664336,28000000000811,28,0,3.623367e+10,4.919216e+06,3.850225e+09,0.018820,0.649435,9.257953,9.585486,10.559112
...,...,...,...,...,...,...,...,...,...,...,...,...
2167,21379521,28000000000001,28,0,1.905425e+12,1.670998e+09,5.368436e+10,0.012449,0.695985,9.048399,10.729848,12.279992
2168,21573586,28000000000002,28,0,1.665042e+12,2.733858e+09,3.504242e+10,0.011764,0.701442,9.020433,10.544594,12.221425
2169,21730535,28000000000003,28,0,1.865954e+12,1.010321e+09,5.163819e+10,0.011853,0.704253,9.021970,10.712971,12.270901
2170,21924775,28000000000004,28,0,8.026573e+11,1.392766e+09,1.918478e+10,0.013734,0.687691,9.096283,10.282957,11.904530
2171,21986361,28000000000005,28,0,1.291893e+12,2.901400e+09,1.332103e+10,0.011223,0.700813,9.000403,10.124538,12.111226

In [12]:
data = {'GalaxyID_test':[],'GroupID_test':[],
        'Lm_snap1':[],'Lm_snap2':[],'Lm_snap3':[],'Lm_snap4':[],
        'Lm_snap5':[],'Lm_snap6':[],'Lm_snap7':[],'Lm_snap8':[],
        'Lm_snap9':[],'Lm_snap10':[],'Lm_snap11':[],'Lm_snap12':[],
        'Lm_snap13':[],'Lm_snap14':[],'Lm_snap15':[],'Lm_snap16':[],
        'Lm_snap17':[],'Lm_snap18':[],'Lm_snap19':[],'Lm_snap20':[],
        'Lm_snap21':[],'Lm_snap22':[],'Lm_snap23':[],'Lm_snap24':[],
        'Lm_snap25':[],'Lm_snap26':[],'Lm_snap27':[],'Lm_snap28':[]}

DATA_merge = pd.DataFrame(data=data)

In [19]:
simu='RefL0100N1504'
snap=28

In [37]:
#long = len(table_a['GalaxyID'])

long = 10

# Usuario y contraseña para conectarse a EAGLE DataBase
usr='cht015'
pwd='BH457tfj'

# Descargar merger tree completo de la galaxia deseada
# Nombre y alias de la tabla de la cual se quieren descargar datos
table='SubHalo'
table_alias='sub'

# Variables que se quiere descargar. OJO!! Asegurarse que estas variables
# estén en la tabla deseada.
columns=[
          'GalaxyID','LastProgID','TopLeafID','DescendantID',
          'SnapNum','Redshift','Stars_Mass','SF_Mass','GroupID'
        ]

#Loop para todas las galaxias de la tabla
for p in np.arange(long):

    galid = table_a['GalaxyID'].to_numpy()[p]
 
    # Descargar todos los IDS necesarios de la galaxia deseada

    myIDs    = mtt.retrieve_ids(usr,pwd,simu,snap,galid)

    raw_tree = mtt.download_merger_tree(usr,pwd,simu,myIDs['GalaxyID'],myIDs['LastProgID'],
                                  table=table,table_alias=table_alias,columns=columns)
    
    # Aplicar condiciones a las galaxias del árbol, si es necesario
    mask = (
            (raw_tree['Stars_Mass']>0)&(raw_tree['SnapNum']>23) #& (raw_tree['Redshift']<2)
           )

    # Armar arbol sólo con galaxias seleccionadas según condiciones anteriores
    tree = {}
    for key in raw_tree.keys():
        tree[key]=raw_tree[key][mask]
        
    # Ordeno las galaxias según SnapNum creciente
    mask_order = (tree['SnapNum']).argsort()
    for key in tree.keys():
        tree[key] = tree[key][mask_order]

    # Armo un diccionario con solo la main branch del árbol
    main_branch = {}
    # Select galaxies in the main branch 
    mask_main = np.logical_and(tree['GalaxyID']>=myIDs['GalaxyID'],
                               tree['GalaxyID']<=myIDs['TopLeafID'])
    
    MAIN_BRANCH  = []

    for key in tree.keys():
        main_branch[key] = tree[key][mask_main]
        MAIN_BRANCH.append(main_branch)

In [39]:
MAIN_BRANCH

[{'GalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780]),
  'LastProgID': array([8685819, 8685855, 8685953, 8686063, 8686187]),
  'TopLeafID': array([8684805, 8684805, 8684805, 8684805, 8684805]),
  'DescendantID': array([8684783, 8684782, 8684781, 8684780, 8684780]),
  'SnapNum': array([24, 25, 26, 27, 28], dtype=int32),
  'Redshift': array([3.6566857e-01, 2.7090108e-01, 1.8270987e-01, 1.0063854e-01,
         2.2204460e-16], dtype=float32),
  'Stars_Mass': array([1.7688502e+10, 1.9089926e+10, 2.0572916e+10, 2.1643680e+10,
         2.3529153e+10], dtype=float32),
  'SF_Mass': array([7.0136192e+09, 7.3412060e+09, 5.9712108e+09, 6.3250381e+09,
         5.5502106e+09], dtype=float32),
  'GroupID': array([24000000001124, 25000000001123, 26000000000989, 27000000000892,
         28000000000862]),
  'SubHaloGalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780])},
 {'GalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780]),
  'LastProgID': array([8685819, 8685855, 8685953, 8686063, 8686187]),
  'TopLeafID': array([8684805, 8684805, 8684805, 8684805, 8684805]),
  'DescendantID': array([8684783, 8684782, 8684781, 8684780, 8684780]),
  'SnapNum': array([24, 25, 26, 27, 28], dtype=int32),
  'Redshift': array([3.6566857e-01, 2.7090108e-01, 1.8270987e-01, 1.0063854e-01,
         2.2204460e-16], dtype=float32),
  'Stars_Mass': array([1.7688502e+10, 1.9089926e+10, 2.0572916e+10, 2.1643680e+10,
         2.3529153e+10], dtype=float32),
  'SF_Mass': array([7.0136192e+09, 7.3412060e+09, 5.9712108e+09, 6.3250381e+09,
         5.5502106e+09], dtype=float32),
  'GroupID': array([24000000001124, 25000000001123, 26000000000989, 27000000000892,
         28000000000862]),
  'SubHaloGalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780])},
 {'GalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780]),
  'LastProgID': array([8685819, 8685855, 8685953, 8686063, 8686187]),
  'TopLeafID': array([8684805, 8684805, 8684805, 8684805, 8684805]),
  'DescendantID': array([8684783, 8684782, 8684781, 8684780, 8684780]),
  'SnapNum': array([24, 25, 26, 27, 28], dtype=int32),
  'Redshift': array([3.6566857e-01, 2.7090108e-01, 1.8270987e-01, 1.0063854e-01,
         2.2204460e-16], dtype=float32),
  'Stars_Mass': array([1.7688502e+10, 1.9089926e+10, 2.0572916e+10, 2.1643680e+10,
         2.3529153e+10], dtype=float32),
  'SF_Mass': array([7.0136192e+09, 7.3412060e+09, 5.9712108e+09, 6.3250381e+09,
         5.5502106e+09], dtype=float32),
  'GroupID': array([24000000001124, 25000000001123, 26000000000989, 27000000000892,
         28000000000862]),
  'SubHaloGalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780])},
 {'GalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780]),
  'LastProgID': array([8685819, 8685855, 8685953, 8686063, 8686187]),
  'TopLeafID': array([8684805, 8684805, 8684805, 8684805, 8684805]),
  'DescendantID': array([8684783, 8684782, 8684781, 8684780, 8684780]),
  'SnapNum': array([24, 25, 26, 27, 28], dtype=int32),
  'Redshift': array([3.6566857e-01, 2.7090108e-01, 1.8270987e-01, 1.0063854e-01,
         2.2204460e-16], dtype=float32),
  'Stars_Mass': array([1.7688502e+10, 1.9089926e+10, 2.0572916e+10, 2.1643680e+10,
         2.3529153e+10], dtype=float32),
  'SF_Mass': array([7.0136192e+09, 7.3412060e+09, 5.9712108e+09, 6.3250381e+09,
         5.5502106e+09], dtype=float32),
  'GroupID': array([24000000001124, 25000000001123, 26000000000989, 27000000000892,
         28000000000862]),
  'SubHaloGalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780])},
 {'GalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780]),
  'LastProgID': array([8685819, 8685855, 8685953, 8686063, 8686187]),
  'TopLeafID': array([8684805, 8684805, 8684805, 8684805, 8684805]),
  'DescendantID': array([8684783, 8684782, 8684781, 8684780, 8684780]),
  'SnapNum': array([24, 25, 26, 27, 28], dtype=int32),
  'Redshift': array([3.6566857e-01, 2.7090108e-01, 1.8270987e-01, 1.0063854e-01,
         2.2204460e-16], dtype=float32),
  'Stars_Mass': array([1.7688502e+10, 1.9089926e+10, 2.0572916e+10, 2.1643680e+10,
         2.3529153e+10], dtype=float32),
  'SF_Mass': array([7.0136192e+09, 7.3412060e+09, 5.9712108e+09, 6.3250381e+09,
         5.5502106e+09], dtype=float32),
  'GroupID': array([24000000001124, 25000000001123, 26000000000989, 27000000000892,
         28000000000862]),
  'SubHaloGalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780])},
 {'GalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780]),
  'LastProgID': array([8685819, 8685855, 8685953, 8686063, 8686187]),
  'TopLeafID': array([8684805, 8684805, 8684805, 8684805, 8684805]),
  'DescendantID': array([8684783, 8684782, 8684781, 8684780, 8684780]),
  'SnapNum': array([24, 25, 26, 27, 28], dtype=int32),
  'Redshift': array([3.6566857e-01, 2.7090108e-01, 1.8270987e-01, 1.0063854e-01,
         2.2204460e-16], dtype=float32),
  'Stars_Mass': array([1.7688502e+10, 1.9089926e+10, 2.0572916e+10, 2.1643680e+10,
         2.3529153e+10], dtype=float32),
  'SF_Mass': array([7.0136192e+09, 7.3412060e+09, 5.9712108e+09, 6.3250381e+09,
         5.5502106e+09], dtype=float32),
  'GroupID': array([24000000001124, 25000000001123, 26000000000989, 27000000000892,
         28000000000862]),
  'SubHaloGalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780])},
 {'GalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780]),
  'LastProgID': array([8685819, 8685855, 8685953, 8686063, 8686187]),
  'TopLeafID': array([8684805, 8684805, 8684805, 8684805, 8684805]),
  'DescendantID': array([8684783, 8684782, 8684781, 8684780, 8684780]),
  'SnapNum': array([24, 25, 26, 27, 28], dtype=int32),
  'Redshift': array([3.6566857e-01, 2.7090108e-01, 1.8270987e-01, 1.0063854e-01,
         2.2204460e-16], dtype=float32),
  'Stars_Mass': array([1.7688502e+10, 1.9089926e+10, 2.0572916e+10, 2.1643680e+10,
         2.3529153e+10], dtype=float32),
  'SF_Mass': array([7.0136192e+09, 7.3412060e+09, 5.9712108e+09, 6.3250381e+09,
         5.5502106e+09], dtype=float32),
  'GroupID': array([24000000001124, 25000000001123, 26000000000989, 27000000000892,
         28000000000862]),
  'SubHaloGalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780])},
 {'GalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780]),
  'LastProgID': array([8685819, 8685855, 8685953, 8686063, 8686187]),
  'TopLeafID': array([8684805, 8684805, 8684805, 8684805, 8684805]),
  'DescendantID': array([8684783, 8684782, 8684781, 8684780, 8684780]),
  'SnapNum': array([24, 25, 26, 27, 28], dtype=int32),
  'Redshift': array([3.6566857e-01, 2.7090108e-01, 1.8270987e-01, 1.0063854e-01,
         2.2204460e-16], dtype=float32),
  'Stars_Mass': array([1.7688502e+10, 1.9089926e+10, 2.0572916e+10, 2.1643680e+10,
         2.3529153e+10], dtype=float32),
  'SF_Mass': array([7.0136192e+09, 7.3412060e+09, 5.9712108e+09, 6.3250381e+09,
         5.5502106e+09], dtype=float32),
  'GroupID': array([24000000001124, 25000000001123, 26000000000989, 27000000000892,
         28000000000862]),
  'SubHaloGalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780])},
 {'GalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780]),
  'LastProgID': array([8685819, 8685855, 8685953, 8686063, 8686187]),
  'TopLeafID': array([8684805, 8684805, 8684805, 8684805, 8684805]),
  'DescendantID': array([8684783, 8684782, 8684781, 8684780, 8684780]),
  'SnapNum': array([24, 25, 26, 27, 28], dtype=int32),
  'Redshift': array([3.6566857e-01, 2.7090108e-01, 1.8270987e-01, 1.0063854e-01,
         2.2204460e-16], dtype=float32),
  'Stars_Mass': array([1.7688502e+10, 1.9089926e+10, 2.0572916e+10, 2.1643680e+10,
         2.3529153e+10], dtype=float32),
  'SF_Mass': array([7.0136192e+09, 7.3412060e+09, 5.9712108e+09, 6.3250381e+09,
         5.5502106e+09], dtype=float32),
  'GroupID': array([24000000001124, 25000000001123, 26000000000989, 27000000000892,
         28000000000862]),
  'SubHaloGalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780])},
 {'GalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780]),
  'LastProgID': array([8685819, 8685855, 8685953, 8686063, 8686187]),
  'TopLeafID': array([8684805, 8684805, 8684805, 8684805, 8684805]),
  'DescendantID': array([8684783, 8684782, 8684781, 8684780, 8684780]),
  'SnapNum': array([24, 25, 26, 27, 28], dtype=int32),
  'Redshift': array([3.6566857e-01, 2.7090108e-01, 1.8270987e-01, 1.0063854e-01,
         2.2204460e-16], dtype=float32),
  'Stars_Mass': array([1.7688502e+10, 1.9089926e+10, 2.0572916e+10, 2.1643680e+10,
         2.3529153e+10], dtype=float32),
  'SF_Mass': array([7.0136192e+09, 7.3412060e+09, 5.9712108e+09, 6.3250381e+09,
         5.5502106e+09], dtype=float32),
  'GroupID': array([24000000001124, 25000000001123, 26000000000989, 27000000000892,
         28000000000862]),
  'SubHaloGalaxyID': array([8684784, 8684783, 8684782, 8684781, 8684780])}]

In [40]:
pd.DataFrame(MAIN_BRANCH)

,GalaxyID,LastProgID,TopLeafID,DescendantID,SnapNum,Redshift,Stars_Mass,SF_Mass,GroupID,SubHaloGalaxyID
0,"[8684784, 8684783, 8684782, 8684781, 8684780]","[8685819, 8685855, 8685953, 8686063, 8686187]","[8684805, 8684805, 8684805, 8684805, 8684805]","[8684783, 8684782, 8684781, 8684780, 8684780]","[24, 25, 26, 27, 28]","[0.36566857, 0.27090108, 0.18270987, 0.1006385...","[1.7688502e+10, 1.9089926e+10, 2.0572916e+10, ...","[7.013619e+09, 7.341206e+09, 5.971211e+09, 6.3...","[24000000001124, 25000000001123, 2600000000098...","[8684784, 8684783, 8684782, 8684781, 8684780]"
1,"[8684784, 8684783, 8684782, 8684781, 8684780]","[8685819, 8685855, 8685953, 8686063, 8686187]","[8684805, 8684805, 8684805, 8684805, 8684805]","[8684783, 8684782, 8684781, 8684780, 8684780]","[24, 25, 26, 27, 28]","[0.36566857, 0.27090108, 0.18270987, 0.1006385...","[1.7688502e+10, 1.9089926e+10, 2.0572916e+10, ...","[7.013619e+09, 7.341206e+09, 5.971211e+09, 6.3...","[24000000001124, 25000000001123, 2600000000098...","[8684784, 8684783, 8684782, 8684781, 8684780]"
2,"[8684784, 8684783, 8684782, 8684781, 8684780]","[8685819, 8685855, 8685953, 8686063, 8686187]","[8684805, 8684805, 8684805, 8684805, 8684805]","[8684783, 8684782, 8684781, 8684780, 8684780]","[24, 25, 26, 27, 28]","[0.36566857, 0.27090108, 0.18270987, 0.1006385...","[1.7688502e+10, 1.9089926e+10, 2.0572916e+10, ...","[7.013619e+09, 7.341206e+09, 5.971211e+09, 6.3...","[24000000001124, 25000000001123, 2600000000098...","[8684784, 8684783, 8684782, 8684781, 8684780]"
3,"[8684784, 8684783, 8684782, 8684781, 8684780]","[8685819, 8685855, 8685953, 8686063, 8686187]","[8684805, 8684805, 8684805, 8684805, 8684805]","[8684783, 8684782, 8684781, 8684780, 8684780]","[24, 25, 26, 27, 28]","[0.36566857, 0.27090108, 0.18270987, 0.1006385...","[1.7688502e+10, 1.9089926e+10, 2.0572916e+10, ...","[7.013619e+09, 7.341206e+09, 5.971211e+09, 6.3...","[24000000001124, 25000000001123, 2600000000098...","[8684784, 8684783, 8684782, 8684781, 8684780]"
4,"[8684784, 8684783, 8684782, 8684781, 8684780]","[8685819, 8685855, 8685953, 8686063, 8686187]","[8684805, 8684805, 8684805, 8684805, 8684805]","[8684783, 8684782, 8684781, 8684780, 8684780]","[24, 25, 26, 27, 28]","[0.36566857, 0.27090108, 0.18270987, 0.1006385...","[1.7688502e+10, 1.9089926e+10, 2.0572916e+10, ...","[7.013619e+09, 7.341206e+09, 5.971211e+09, 6.3...","[24000000001124, 25000000001123, 2600000000098...","[8684784, 8684783, 8684782, 8684781, 8684780]"
5,"[8684784, 8684783, 8684782, 8684781, 8684780]","[8685819, 8685855, 8685953, 8686063, 8686187]","[8684805, 8684805, 8684805, 8684805, 8684805]","[8684783, 8684782, 8684781, 8684780, 8684780]","[24, 25, 26, 27, 28]","[0.36566857, 0.27090108, 0.18270987, 0.1006385...","[1.7688502e+10, 1.9089926e+10, 2.0572916e+10, ...","[7.013619e+09, 7.341206e+09, 5.971211e+09, 6.3...","[24000000001124, 25000000001123, 2600000000098...","[8684784, 8684783, 8684782, 8684781, 8684780]"
6,"[8684784, 8684783, 8684782, 8684781, 8684780]","[8685819, 8685855, 8685953, 8686063, 8686187]","[8684805, 8684805, 8684805, 8684805, 8684805]","[8684783, 8684782, 8684781, 8684780, 8684780]","[24, 25, 26, 27, 28]","[0.36566857, 0.27090108, 0.18270987, 0.1006385...","[1.7688502e+10, 1.9089926e+10, 2.0572916e+10, ...","[7.013619e+09, 7.341206e+09, 5.971211e+09, 6.3...","[24000000001124, 25000000001123, 2600000000098...","[8684784, 8684783, 8684782, 8684781, 8684780]"
7,"[8684784, 8684783, 8684782, 8684781, 8684780]","[8685819, 8685855, 8685953, 8686063, 8686187]","[8684805, 8684805, 8684805, 8684805, 8684805]","[8684783, 8684782, 8684781, 8684780, 8684780]","[24, 25, 26, 27, 28]","[0.36566857, 0.27090108, 0.18270987, 0.1006385...","[1.7688502e+10, 1.9089926e+10, 2.0572916e+10, ...","[7.013619e+09, 7.341206e+09, 5.971211e+09, 6.3...","[24000000001124, 25000000001123, 2600000000098...","[8684784, 8684783, 8684782, 8684781, 8684780]"
8,"[8684784, 8684783, 8684782, 8684781, 8684780]","[8685819, 8685855, 8685953, 8686063, 8686187]","[8684805, 8684805, 8684805, 8684805, 8684805]","[8684783, 8684782, 8684781, 8684780, 8684780]","[24, 25, 26, 27, 28]","[0.36566857, 0.27090108, 0.18270987, 0.1006385...","[1.7688502e+10, 1.9089926e+10, 2.0572916e+10, ...","[7.013619e+09, 7.341206e+09, 5.971211e+09, 6.3...","[24000000001124, 25000000001123, 2600000000098...","[8684784, 8684783, 8684782, 8684781, 8684780]"
9,"[8684784, 8684783, 8684782, 8684781, 8684780]","[8685819, 8685855, 8685953, 8686063, 8686187]","[8684805, 8684805, 8684805, 8684805, 8684805]","[8684783, 8684782, 8684781, 8684780, 8684780]","[24, 25, 26, 27, 28]","[0.36566857, 0.27090108, 0.18270987, 0.1006385...","[1.7688502e+10, 1.9089926e+10, 2.0572916e+10, ...","[7.013619e+09, 7.341206e+09, 5.971211e+09, 6.3...","[24000000001124, 25000000001123, 2600000000098...","[8684784, 8684783, 8684782, 8684781, 8684780]"

In [32]:
lookbacktime = [0,1.35,2.32,3.24,4.12,5.22,5.98,6.69,7.35,7.96,8.86,9.49,10.05,10.54,10.87,11.17,11.68]
for i in range(len(lookbacktime)-1):
    print(f'Entre {lookbacktime[i]} y {lookbacktime[i+1]} Gyr hay {-lookbacktime[i]+lookbacktime[i+1]} Gyr')

Entre 0 y 1.35 Gyr hay 1.35 Gyr
Entre 1.35 y 2.32 Gyr hay 0.9699999999999998 Gyr
Entre 2.32 y 3.24 Gyr hay 0.9200000000000004 Gyr
Entre 3.24 y 4.12 Gyr hay 0.8799999999999999 Gyr
Entre 4.12 y 5.22 Gyr hay 1.0999999999999996 Gyr
Entre 5.22 y 5.98 Gyr hay 0.7600000000000007 Gyr
Entre 5.98 y 6.69 Gyr hay 0.71 Gyr
Entre 6.69 y 7.35 Gyr hay 0.6599999999999993 Gyr
Entre 7.35 y 7.96 Gyr hay 0.6100000000000003 Gyr
Entre 7.96 y 8.86 Gyr hay 0.8999999999999995 Gyr
Entre 8.86 y 9.49 Gyr hay 0.6300000000000008 Gyr
Entre 9.49 y 10.05 Gyr hay 0.5600000000000005 Gyr
Entre 10.05 y 10.54 Gyr hay 0.48999999999999844 Gyr
Entre 10.54 y 10.87 Gyr hay 0.33000000000000007 Gyr
Entre 10.87 y 11.17 Gyr hay 0.3000000000000007 Gyr
Entre 11.17 y 11.68 Gyr hay 0.5099999999999998 Gyr

In [10]:
long = len(table_a['GalaxyID'])

# long = 10

# Usuario y contraseña para conectarse a EAGLE DataBase
usr='cht015'
pwd='BH457tfj'

# Descargar merger tree completo de la galaxia deseada
# Nombre y alias de la tabla de la cual se quieren descargar datos
table='SubHalo'
table_alias='sub'

# Variables que se quiere descargar. OJO!! Asegurarse que estas variables
# estén en la tabla deseada.
columns=[
          'GalaxyID','LastProgID','TopLeafID','DescendantID',
          'SnapNum','Redshift','Stars_Mass','SF_Mass','GroupID'
        ]

#Loop para todas las galaxias de la tabla
for p in np.arange(long):

    galid = table_a['GalaxyID'].to_numpy()[p]
 
    # Descargar todos los IDS necesarios de la galaxia deseada

    myIDs    = mtt.retrieve_ids(usr,pwd,simu,snap,galid)

    raw_tree = mtt.download_merger_tree(usr,pwd,simu,myIDs['GalaxyID'],myIDs['LastProgID'],
                                  table=table,table_alias=table_alias,columns=columns)
    
    # Aplicar condiciones a las galaxias del árbol, si es necesario
    mask = (
            (raw_tree['Stars_Mass']>0)
           )

    # Armar arbol sólo con galaxias seleccionadas según condiciones anteriores
    tree = {}
    for key in raw_tree.keys():
        tree[key]=raw_tree[key][mask]
        
    # Ordeno las galaxias según SnapNum creciente
    mask_order = (tree['SnapNum']).argsort()
    for key in tree.keys():
        tree[key] = tree[key][mask_order]

    # Armo un diccionario con solo la main branch del árbol
    main_branch = {}
    # Select galaxies in the main branch 
    mask_main = np.logical_and(tree['GalaxyID']>=myIDs['GalaxyID'],
                               tree['GalaxyID']<=myIDs['TopLeafID']) 

    for key in tree.keys():
        main_branch[key] = tree[key][mask_main]

        
    xplot_main = main_branch['SnapNum']
    
    # Calculo level of merger
    level_merger=[1]       # Inicializo con un 1, porque la primer galaxia del main branch 
                           # no viene de ninguna fusión...
    
    for k in range(np.size(xplot_main)-1):
        m1=main_branch['Stars_Mass'][k]+main_branch['SF_Mass'][k]
        mask=(tree['DescendantID']==main_branch['GalaxyID'][k+1]) & (tree['SnapNum']!=28) 
        # La condición de snapnum distinto a 28 es porque galaxias a z=0 no tienen descendiente,
        # y se les asigna como DescendantID su propio GalaxyID
        m2=np.sum(tree['Stars_Mass'][mask])+np.sum(tree['SF_Mass'][mask])
        level=m2/m1
        level_merger=np.append(level_merger,level)  
        
    #Calculamos las variables que nos interesan:
    
    i=0 

    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==1)):
        Lm_1 = level_merger[i]
        i=i+1
    else: Lm_1 = np.nan
    
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==2)):
        Lm_2 = level_merger[i]
        i=i+1
    else: Lm_2 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==3)):
        Lm_3 = level_merger[i]
        i=i+1
    else: Lm_3 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==4)):
        Lm_4 = level_merger[i]
        i=i+1
    else: Lm_4 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==5)):
        Lm_5 = level_merger[i]
        i=i+1
    else: Lm_5 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==6)):
        Lm_6 = level_merger[i]
        i=i+1
    else: Lm_6 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==7)):
        Lm_7 = level_merger[i]
        i=i+1
    else: Lm_7 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==8)):
        Lm_8 = level_merger[i]
        i=i+1
    else: Lm_8 = np.nan
    
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==9)):
        Lm_9 = level_merger[i]
        i=i+1
    else: Lm_9 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==10)):
        Lm_10 = level_merger[i]
        i=i+1
    else: Lm_10 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==11)):
        Lm_11 = level_merger[i]
        i=i+1
    else: Lm_11 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==12)):
        Lm_12 = level_merger[i]
        i=i+1
    else: Lm_12 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==13)):
        Lm_13 = level_merger[i]
        i=i+1
    else: Lm_13 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==14)):
        Lm_14 = level_merger[i]
        i=i+1
    else: Lm_14 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==15)):
        Lm_15 = level_merger[i]
        i=i+1
    else: Lm_15 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==16)):
        Lm_16 = level_merger[i]
        i=i+1
    else: Lm_16 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==17)):
        Lm_17 = level_merger[i]
        i=i+1
    else: Lm_17 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==18)):
        Lm_18 = level_merger[i]
        i=i+1
    else: Lm_18 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==19)):
        Lm_19 = level_merger[i]
        i=i+1
    else: Lm_19 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==20)):
        Lm_20 = level_merger[i]
        i=i+1
    else: Lm_20 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==21)):
        Lm_21 = level_merger[i]
        i=i+1
    else: Lm_21 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==22)):
        Lm_22 = level_merger[i]
        i=i+1
    else: Lm_22 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==23)):
        Lm_23 = level_merger[i]
        i=i+1
    else: Lm_23 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==24)):
        Lm_24 = level_merger[i]
        i=i+1
    else: Lm_24 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==25)):
        Lm_25 = level_merger[i]
        i=i+1
    else: Lm_25 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==26)):
        Lm_26 = level_merger[i]
        i=i+1
    else: Lm_26 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==27)):
        Lm_27 = level_merger[i]
        i=i+1
    else: Lm_27 = np.nan
        
    if ((i<=len(main_branch['SnapNum'])-1)and(main_branch['SnapNum'][i]==28)):
        Lm_28 = level_merger[i]
        i=i+1
    else: Lm_28 = np.nan
   
    
    
    


    data = {'GalaxyID_test':table_a['GalaxyID'].to_numpy()[p],'GroupID_test':table_a['GroupID'].to_numpy()[p],
            'Lm_snap1':Lm_1,'Lm_snap2':Lm_2,'Lm_snap3':Lm_3,'Lm_snap4':Lm_4,
            'Lm_snap5':Lm_5,'Lm_snap6':Lm_6,'Lm_snap7':Lm_7,'Lm_snap8':Lm_8,
            'Lm_snap9':Lm_9,'Lm_snap10':Lm_10,'Lm_snap11':Lm_11,'Lm_snap12':Lm_12,
            'Lm_snap13':Lm_13,'Lm_snap14':Lm_14,'Lm_snap15':Lm_15,'Lm_snap16':Lm_16,
            'Lm_snap17':Lm_17,'Lm_snap18':Lm_18,'Lm_snap19':Lm_19,'Lm_snap20':Lm_20,
            'Lm_snap21':Lm_21,'Lm_snap22':Lm_22,'Lm_snap23':Lm_23,'Lm_snap24':Lm_24,
            'Lm_snap25':Lm_25,'Lm_snap26':Lm_26,'Lm_snap27':Lm_27,'Lm_snap28':Lm_28}

    DATA_merge = DATA_merge.append(data,ignore_index=True)
    
    print('Porcentaje:',round(float((p+1)/long),2),end='\r')

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

/tmp/ipykernel_2516/1727684257.py:231: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DATA_merge = DATA_merge.append(data,ignore_index=True)

In [11]:
DATA_merge = DATA_merge.astype({'GalaxyID_test':int,'GroupID_test':int,
                                'Lm_snap1':float, 'Lm_snap2':float, 'Lm_snap3':float, 'Lm_snap4':float,
                                'Lm_snap5':float, 'Lm_snap6':float, 'Lm_snap7':float, 'Lm_snap8':float,
                                'Lm_snap9':float, 'Lm_snap10':float,'Lm_snap11':float,'Lm_snap12':float,
                                'Lm_snap13':float,'Lm_snap14':float,'Lm_snap15':float,'Lm_snap16':float,
                                'Lm_snap17':float,'Lm_snap18':float,'Lm_snap19':float,'Lm_snap20':float,
                                'Lm_snap21':float,'Lm_snap22':float,'Lm_snap23':float,'Lm_snap24':float,
                                'Lm_snap25':float,'Lm_snap26':float,'Lm_snap27':float,'Lm_snap28':float})

In [12]:
DATA_merge

,GalaxyID_test,GroupID_test,Lm_snap1,Lm_snap2,Lm_snap3,Lm_snap4,Lm_snap5,Lm_snap6,Lm_snap7,Lm_snap8,Lm_snap9,Lm_snap10,Lm_snap11,Lm_snap12,Lm_snap13,Lm_snap14,Lm_snap15,Lm_snap16,Lm_snap17,Lm_snap18,Lm_snap19,Lm_snap20,Lm_snap21,Lm_snap22,Lm_snap23,Lm_snap24,Lm_snap25,Lm_snap26,Lm_snap27,Lm_snap28
0,2422553,28000000000045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,153.395920,1.027606,1.000000,15.033673,1.150702,1.123952
1,2794037,28000000000077,NaN,1.0,1.0,1.000000,1.141045,1.000000,1.000000,1.000000,1.000000,1.000000,1.291500,1.130867,1.027379,1.004284,1.001929,1.078370,1.060465,1.001958,1.396046,1.005928,1.064743,1.000027,1.011130,1.002825,1.000144,1.000000,1.000045,1.003087
2,2874743,28000000000089,NaN,1.0,1.0,1.000000,1.000000,1.020554,1.000000,1.049220,1.015175,1.461086,1.016436,1.005843,1.012017,1.044937,1.000910,1.002344,1.032843,1.020746,1.020869,1.047031,1.033631,1.035837,1.011820,1.027238,1.035833,1.033938,1.024504,1.029082
3,2909752,28000000000095,NaN,NaN,1.0,1.134469,1.000000,1.027000,1.010348,1.166992,1.000000,1.093654,1.000000,1.003629,1.370386,1.007201,1.136142,1.000924,1.011405,1.014178,1.022613,1.444742,1.016895,1.012665,1.001377,1.002495,1.025546,1.000062,1.000015,1.001780
4,2916107,28000000000096,NaN,NaN,1.0,2.265458,1.000000,1.000000,1.000000,1.000000,1.028105,1.000000,1.009491,1.012380,1.220577,1.000000,1.008914,1.002928,1.239389,1.007780,1.077727,1.044760,1.045833,1.020605,1.020927,1.013415,1.023750,1.015586,1.002842,1.323763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,3315360,28000000000187,NaN,NaN,NaN,NaN,1.000000,1.043361,1.000000,1.000000,1.023095,1.004088,1.223981,1.004166,1.011469,1.002048,1.000000,1.035604,1.016533,1.006515,1.069634,1.000148,1.003545,1.000160,1.038024,1.005880,1.000000,1.002134,1.000000,1.001991
52,3333632,28000000000193,NaN,NaN,1.0,5.095816,1.065282,1.000000,1.000000,1.008364,1.013828,1.004306,1.000000,1.007369,1.447163,1.001745,1.000000,1.018839,1.000958,1.000104,1.032601,1.027498,1.000136,1.000000,1.004195,1.000068,1.004729,1.000060,1.000000,1.000938
53,3421831,28000000000225,NaN,NaN,NaN,1.000000,1.000000,1.146278,1.036119,1.000000,1.059989,1.035235,1.120506,1.018946,1.031421,1.020391,1.032650,1.147804,1.065748,1.014035,1.013312,1.007095,1.002940,1.000032,1.000000,1.000000,1.000000,1.161767,1.000000,1.000000
54,3434066,28000000000230,NaN,1.0,1.0,1.000000,2.628286,1.008435,1.101922,1.001453,1.001437,1.005285,1.003487,1.000000,1.001627,1.000294,1.019341,1.000000,1.012679,1.000305,1.000292,1.011676,1.017289,1.003540,1.030852,1.017014,1.034362,1.034623,1.035313,1.024727
55,3466406,28000000000244,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.485565,1.000000,1.645220,1.000000,1.158157,1.066742,1.000000,1.003230,1.000788,1.000614,1.001363,1.001163,1.112413,1.068572,1.352761,1.007027,1.000097,1.000000,1.000000,1.000000,1.000000

In [13]:
DATA_merge.to_csv(path_or_buf= path_lin+'/Merger_history_altas_masas_mayores_a_10_NoAGNL0050N0752_snap_28.dat',index=False) # Nos guardamos los datos

In [14]:
table_a.to_csv(path_or_buf= path_lin+'/bin_proyecto_altas_masas_mayores_a_10_NoAGNL0050N0752_snap_28.dat',index=False)

* Snapshot 19 = Redshift 1
* Snapshot 28 = Redshift 0

## Pruebas fraction of merger

In [3]:
DATA_merge  = pd.read_csv(path_lin+'/Actividad_8(merger_history_tesis).dat')

In [20]:
mask = (DATA_merge['Lm_snap6'] == 0)
DATA_merge[mask]

,GalaxyID_test,GroupID_test,Lm_snap1,Lm_snap2,Lm_snap3,Lm_snap4,Lm_snap5,Lm_snap6,Lm_snap7,Lm_snap8,...,Lm_snap19,Lm_snap20,Lm_snap21,Lm_snap22,Lm_snap23,Lm_snap24,Lm_snap25,Lm_snap26,Lm_snap27,Lm_snap28
7,2727611,28000000000002,NaN,NaN,1.0,NaN,NaN,0.0,1.891800,1.000000,...,1.018315,1.033089,1.068498,1.000000,NaN,NaN,NaN,0.00000,NaN,NaN
14,4470669,28000000000004,NaN,NaN,1.0,1.0,NaN,0.0,1.000000,1.000000,...,1.023634,1.000000,1.027689,1.029271,1.015195,1.006829,1.000000,1.00000,1.000000,NaN
18,10507082,28000000002364,NaN,NaN,1.0,NaN,NaN,0.0,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000
24,10352660,28000000002189,NaN,NaN,1.0,1.0,NaN,0.0,1.000000,1.000000,...,1.000000,1.474600,1.333145,1.000000,1.000000,1.007035,1.000000,1.00000,1.000000,1.000000
34,21793,28000000000000,NaN,1.0,NaN,NaN,NaN,0.0,2.658798,1.000000,...,1.043703,1.000000,1.004681,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,8667711,28000000000817,NaN,1.0,NaN,NaN,NaN,0.0,1.000000,1.000000,...,1.047138,1.029600,1.006176,1.000000,1.037501,1.012499,1.000626,1.00000,1.000000,1.000000
3602,18385552,28000000001003,NaN,1.0,NaN,NaN,NaN,0.0,1.000000,1.000000,...,1.000000,1.010950,1.016656,1.026810,1.010499,1.007426,1.011448,1.00701,1.009407,1.017955
3614,2979098,28000000001336,NaN,NaN,NaN,1.0,NaN,0.0,1.000000,1.000000,...,1.000000,1.000000,1.006409,1.000000,1.000000,1.023178,1.007344,1.00000,1.033620,1.016327
3622,9733375,28000000001609,NaN,NaN,1.0,NaN,NaN,0.0,1.000000,1.000000,...,1.042202,1.000000,1.000000,1.000000,1.000000,1.003019,1.000000,1.00000,1.000000,1.022765
3623,9861180,28000000001714,NaN,NaN,1.0,NaN,NaN,0.0,1.250106,1.190671,...,1.019086,1.000000,1.000000,1.000000,1.005158,1.000000,1.000000,1.00000,1.000000,1.000000

In [ ]:
# Fin